# Generated by Django 2.1.7 on 2020-04-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0007_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
