# Generated by Django 2.1.7 on 2019-10-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='message',
            field=models.CharField(default=1, max_length=255, verbose_name='コメント'),
            preserve_default=False,
        ),
    ]
