# Generated by Django 2.1.7 on 2019-10-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='comment',
        ),
    ]
