# Generated by Django 2.1.7 on 2019-10-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191019_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='message',
            field=models.CharField(max_length=255, verbose_name='メッセ―ジ'),
        ),
    ]
