# Generated by Django 2.1.7 on 2019-10-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191019_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='comment',
        ),
    ]
