# Generated by Django 2.1.7 on 2019-10-22 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191019_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category'),
        ),
    ]
