# Generated by Django 2.1.7 on 2019-10-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191022_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mes',
            field=models.CharField(default=1, max_length=255, verbose_name='メッセ―ジ'),
            preserve_default=False,
        ),
    ]
