# Generated by Django 2.1.7 on 2019-10-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_comment_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mes',
            field=models.CharField(max_length=255, verbose_name='題名'),
        ),
    ]
