# Generated by Django 2.1.7 on 2020-04-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200406_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='genre',
            field=models.CharField(default=1, max_length=100, verbose_name='会社名'),
            preserve_default=False,
        ),
    ]
