# Generated by Django 2.1.7 on 2020-04-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200408_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='category',
            new_name='引率者',
        ),
    ]
