# Generated by Django 2.1.7 on 2020-04-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200408_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='引率者',
            new_name='category',
        ),
    ]
