# Generated by Django 2.1.7 on 2020-04-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20200408_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='message',
            field=models.CharField(max_length=255, verbose_name='得意分野'),
        ),
    ]
