# Generated by Django 2.1.7 on 2020-04-11 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20200411_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('org', models.CharField(max_length=100, verbose_name='会社名')),
                ('scale', models.CharField(max_length=100, verbose_name='人数規模')),
                ('proposals', models.CharField(max_length=100, verbose_name='提案数')),
                ('mat_trend', models.CharField(max_length=100, verbose_name='案件傾向')),
                ('mat_total', models.CharField(max_length=100, verbose_name='案件総数')),
                ('priority', models.CharField(max_length=100, verbose_name='優先度')),
                ('memo', models.CharField(max_length=100, verbose_name='詳細メモ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
