# Generated by Django 2.1.7 on 2020-04-13 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
