# Generated by Django 2.1.7 on 2020-04-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='memo',
            field=models.TextField(default=1, max_length=1000, verbose_name='社員'),
            preserve_default=False,
        ),
    ]
