# Generated by Django 2.1.7 on 2020-04-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_category_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='memo',
            field=models.TextField(max_length=1000, verbose_name='社員メモ'),
        ),
    ]
